<?php

namespace SacBundle\Repository;

use SacBundle\Entity\IChamado;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityRepository;

/**
 * ChamadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChamadoRepository extends EntityRepository implements IChamadoRepository
{

    public function busca(IChamado $entity, $pag, $limit)
    {
        $qb = $this->createQueryBuilder("c");
        if($entity->getPedido()->getNumPedido()) {
            $qb->leftJoin('c.pedido', 'p')
                ->where("p.numPedido = :numPedido")
                ->setParameter("numPedido", $entity->getPedido()->getNumPedido());
        }
        if($entity->getCliente()->getEmail()) {
            $qb->leftJoin('c.cliente', 'cl')
                ->andWhere("cl.email = :email")
                ->setParameter("email", $entity->getCliente()->getEmail());
        }
        $qb->orderBy("c.id", 'DESC');
        $query = $qb->getQuery();
        $result = $this->paginate($query,$pag,$limit);

        return $result;
    }


    public function paginate($dql, $page = 1, $limit = 5)
    {
        $paginator = new Paginator($dql);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1)) // Offset
            ->setMaxResults($limit); // Limit

        return $paginator;
    }
}
