<?php

namespace SacBundle\Repository;
use SacBundle\Entity\IPedido;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends \Doctrine\ORM\EntityRepository implements IPedidoRepository
{
}
